[build] 
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.66.0" # if older, use format: 0.53 (no trailing zero)
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/newsletter"
  to = "https://wordpress.us15.list-manage.com/subscribe?u=32633324b455abb9ac78e47be&id=75ec2fa59f"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
